#
# fetch .tar.gz files
#

- stat:
    path: "{{ metricbeat_download_path }}/{{ metricbeat_tarball }}.tar.gz"
  register: st

- debug: msg="Download {{ metricbeat_tarball_url }} to {{ metricbeat_download_path }}/{{ metricbeat_tarball }}.tar.gz"

- name: get Metricbeat tarball (as tar.gz file)
  get_url:
    url:     "{{ metricbeat_tarball_url }}"
    dest:    "{{ metricbeat_download_path }}/{{ metricbeat_tarball }}.tar.gz"
    mode:    0644
  when: metricbeat_download_from_remote and not st.stat.exists

