---

- include: tasks/set-role-variables.yml

- name: Install Filebeat
  include: install.yml
  tags:
    - build

- name: Configure Filebeat
  include: configure.yml
  tags:
    - configure

# - name: Ensure Filebeat is started and enabled at boot.
#   service:
#     name: filebeat
#     state: started
#     enabled: yes

- name: Restart filebeat
  supervisorctl:
    name: filebeat
    state: present

- name: Restart filebeat
  shell: "steve -k restart -s filebeat"
  become: True
  tags: ["setup"]


- name: Remove tmp files
  become: yes
  file:
    path: "/tmp/{{ filebeat_tarball }}"
    state: absent
    