---

- include: tasks/set-role-variables.yml

- name: Install Metricbeat
  include: install.yml
  tags:
    - build

- name: Configure Metricbeat
  include: configure.yml
  tags:
    - configure

- name: Restart Metricbeat
  supervisorctl:
    name: metricbeat
    state: present

- name: Restart metricbeat
  shell: "steve -k restart -s metricbeat"
  become: True
  tags: ["setup"]


- name: Remove tmp files
  become: yes
  file:
    path: "/tmp/{{ metricbeat_tarball }}"
    state: absent
    