---
# file: tasks/set-role-variables.yml
# set necessary role variables.
#

- name: compose url for downloading file, if necessary
  set_fact:
    metricbeat_tarball: metricbeat-{{ metricbeat_version }}-linux-x86_64
- name: compose url for downloading file, if necessary
  set_fact:
    metricbeat_tarball_url:  "{{ metricbeat_download_base_url }}/{{ metricbeat_tarball }}.tar.gz"

