---
# file: tasks/set-role-variables.yml
# set necessary role variables.
#

- name: compose url for downloading file, if necessary
  set_fact:
    filebeat_tarball: filebeat-{{ filebeat_version }}-linux-x86_64
- name: compose url for downloading file, if necessary
  set_fact:
    filebeat_tarball_url:  "{{ filebeat_download_base_url }}/{{ filebeat_tarball }}.tar.gz"

