---


# - name: restart filebeat
#   service: name=filebeat state=restarted
#   when: ansible_service_mgr is defined and ansible_service_mgr == 'systemd'

- name: restart filebeat
  shell: "steve -k restart -s filebeat"
  become: True
  tags: ["update"]
